{% set name = "esbonio" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/esbonio-{{ version }}.tar.gz
  sha256: edbeeb22022472d936769f9fc58b96372f71ae2b490f6d4d12b2f7587cb75051

build:
  entry_points:
    - esbonio = esbonio.__main__:main
    - esbonio-sphinx = esbonio.lsp.sphinx.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - appdirs
    - pygls >=0.11.2
    - pyspellchecker
    - python >=3.6
    - sphinx
    - typing-extensions

test:
  imports:
    - esbonio.lsp
  commands:
    - pip check
    - esbonio --help
    - esbonio-sphinx --help
  requires:
    - pip

about:
  home: https://swyddfa.github.io/esbonio/
  summary: A Language Server for Sphinx projects.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/swyddfa/esbonio

extra:
  recipe-maintainers:
    - alcarney
